[project]
name = "basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=0.201.0",
    "crewai-tools>=0.75.0",
    "dotenv>=0.9.9",
    "pyyaml>=6.0.3",
]
